eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411/
hystrix:
  metrics:
    enabled: true
feign:
  client:
    config:
      cloud-user:
        connectTimeout: 1000
